### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by JIzabal** [mtang24/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - Fix the last step so that the command copies and runs the code on the remote server: Part 7 – Making Remote Running Even More Pleasant (this is from the lab in week 1) - Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by mtang24** [comment]
I'm confused on what I am supposed to do to make a local edit to WhereAmI.java. Does that mean I just change some random lines in the file on my computer and then copy it to the server?

**Comment by JIzabal** [comment]
No worries! We want you to create a command that copies your java file to your remote server (i.e., Not on your machine), compiles it on the remote server, and then runs it on the remote server. In other words, you don't actually need to make an edit, we just want you to create a command that does all the above. Check out Part 5 in Lab 1 to see how to copy a file over to a remote server, and then look at Part 7 to see how to run a command on the remote server. Once you figure out how to do those things, you can combine multiple commands using semicolons to create one long command that copies your file to the remote server, compiles it there, and runs it there. After running that command once, you can click the up key on your keyboard to see it again and click enter to run it. Consider how many keystrokes this takes (i.e., How many times you press a button on your keyboard and click the mouse), and that should be what you write down along with the command you used. Let me know if you have any more questions!

**Comment by mtang24** [comment]
How does this look? Am I on the right track? 
https://mtang24.github.io/cse15l-lab-reports/lab-report-1-week-2.html 
![image](https://user-images.githubusercontent.com/74260331/151481628-0c0a8e80-44fe-4e71-a1eb-05f6b40113c5.png)

**Comment by mtang24** [comment]
I made some further updates including keystrokes. Please let me know if it looks okay: 
https://mtang24.github.io/cse15l-lab-reports/lab-report-1-week-2.html

**Comment by JIzabal** [comment]
Great work!
